// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1IinFw3k993M6sBfWrqLTtyVgaBq4oIo',
    appId: '1:696176110578:android:ab79871a4cb6f669ed996b',
    messagingSenderId: '696176110578',
    projectId: 'movie-app-10f70',
    storageBucket: 'movie-app-10f70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBfWMfrKY7e2vsYh4JyXqX-wCBtczRS08',
    appId: '1:696176110578:ios:e4def2a89b747d07ed996b',
    messagingSenderId: '696176110578',
    projectId: 'movie-app-10f70',
    storageBucket: 'movie-app-10f70.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBfWMfrKY7e2vsYh4JyXqX-wCBtczRS08',
    appId: '1:696176110578:ios:1deae5ca5839ab6aed996b',
    messagingSenderId: '696176110578',
    projectId: 'movie-app-10f70',
    storageBucket: 'movie-app-10f70.appspot.com',
    iosBundleId: 'com.example.flutterProject.RunnerTests',
  );
}
